# CircleCI Configuration file

machine:
  python:
    version: 2.7.11
  environment:
    PATH: "$HOME/miniconda/bin:$PATH"

general:
  artifacts:
    - "dist"

dependencies:
  override:
    - pip install tox tox-pyenv flake8
    - pyenv local 2.7.11 3.5.2 3.6.2 # Should correspond to pre-installed Python versions on CircleCI

test:
  override:
    - flake8 floyd
    - tox

deployment:
  pypi:
    branch: /release.*/
    owner: floydhub
    commands:
      - echo "[distutils]" > ~/.pypirc
      - echo "index-servers =" >> ~/.pypirc
      - echo "    pypi" >> ~/.pypirc
      - echo >> ~/.pypirc
      - echo "[pypi]" >> ~/.pypirc
      - echo "username:$PYPI_USERNAME" >> ~/.pypirc
      - echo "password:$PYPI_PASSWORD" >> ~/.pypirc
      - echo >> ~/.pypirc
      - python setup.py register -r pypi
      - python setup.py sdist upload -r pypi
      # Run conda release now
      # Install conda, conda-build, and anaconda-client
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p $HOME/miniconda
      - conda config --set always_yes yes
      - conda config --add channels conda-forge
      - conda install conda-build
      - conda install anaconda-client
      # Build the package for python 2.7, 3.5, and 3.6
      - conda build --python 2.7 conda
      - conda build --python 3.5 conda
      - conda build --python 3.6 conda
      # Create the build for each OS and architecture (for each 2.7, 3.5, and 3.6)
      - cp -r $HOME/miniconda/conda-bld/linux-64 .
      - conda convert -p all `ls linux-64/floyd-cli-*-py27*.tar.bz2` # 2.7
      - conda convert -p all `ls linux-64/floyd-cli-*-py35*.tar.bz2` # 3.5
      - conda convert -p all `ls linux-64/floyd-cli-*-py36*.tar.bz2` # 3.6
      # Upload all 2.7 versions to anaconda.org
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-64/floyd-cli-*-py27*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-32/floyd-cli-*-py27*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-32/floyd-cli-*-py27*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-64/floyd-cli-*-py27*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls osx-64/floyd-cli-*-py27*.tar.bz2`
      # Upload all 3.5 versions to anaconda.org
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-64/floyd-cli-*-py35*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-32/floyd-cli-*-py35*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-32/floyd-cli-*-py35*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-64/floyd-cli-*-py35*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls osx-64/floyd-cli-*-py35*.tar.bz2`
      # Upload all 3.6 versions to anaconda.org
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-64/floyd-cli-*-py36*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls linux-32/floyd-cli-*-py36*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-32/floyd-cli-*-py36*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls win-64/floyd-cli-*-py36*.tar.bz2`
      - anaconda -t $ANACONDA_TOKEN upload --force `ls osx-64/floyd-cli-*-py36*.tar.bz2`
