# CircleCI Configuration file

version: 2

jobs:
    test-py27:
        docker:
            - image: python:2.7.11
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: pip install tox tox-pyenv flake8
            - run:
                name: Test
                command: |
                    flake8 floyd
                    tox -e py27

    test-py35:
        docker:
            - image: python:3.5.2
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: pip install tox tox-pyenv flake8
            - run:
                name: Test
                command: |
                    flake8 floyd
                    tox -e py35

    test-py36:
        docker:
            - image: python:3.6.2
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: pip install tox tox-pyenv flake8
            - run:
                name: Test
                command: |
                    flake8 floyd
                    tox -e py36

workflows:
    version: 2
    build:
        jobs:
            - test-py27
            - test-py35
            - test-py36
