# CircleCI Configuration file

version: 2
jobs:
  build:
    docker:
        - image: python:2.7.11
      # python:
      #   version: 2.7.11
      # environment:
      #   PATH: "$HOME/miniconda/bin:$PATH"
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: pip install tox tox-pyenv flake8
        - run:
            name: Test
            command: |
                flake8 floyd
                tox -e py27
        - store_artifacts:
            path: dist
