# CircleCI Configuration file

version: 2
jobs:
  build:
    machine:
      python:
        version: 2.7.11
      environment:
        PATH: "$HOME/miniconda/bin:$PATH"
    steps:
        - run:
            name: Install dependencies
            command: pip install tox tox-pyenv flake8
        - run:
            name: Install pyenv versions
            command: pyenv local 2.7.11 3.5.2 3.6.2
        - run:
            name: Test
            command: |
                flake8 floyd
                tox
        - store_artifacts:
            path: /dist
