# CircleCI Configuration file

version: 2

shared: &shared
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: pip install tox tox-pyenv flake8
        - run:
            name: Test
            command: |
                flake8 floyd
                tox -e py27
        - store_artifacts:
            path: dist

jobs:
    py27:
        <<: *shared
        docker:
            - image: python:2.7.11

    py35:
        <<: *shared
        docker:
            - image: python:3.5.2


workflows:
    version: 2
    build:
        jobs:
            - py27
            - py35
