{% set name = "floyd-cli" %}
{% set version = "0.10.33" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 0
  entry_points:
    - floyd = floyd.main:cli
    - floyd-dev = floyd.development.dev:cli
    - floyd-local = floyd.development.local:cli

requirements:
  build:
    - python
    - setuptools
    - click >=6.7,<7
    - clint >=0.5.1,<1
    - requests >=2.12.4,<3
    - requests-toolbelt >=0.7.1,<1
    - marshmallow >=2.11.1,<3
    - pytz >=2016.10
    - tabulate >=0.7.7,<1
    - pathlib2 >=2.2.1,<3
    - raven
  run:
    - python
    - click >=6.7,<7
    - clint >=0.5.1,<1
    - requests >=2.12.4,<3
    - requests-toolbelt >=0.7.1,<1
    - marshmallow >=2.11.1,<3
    - pytz >=2016.10
    - tabulate >=0.7.7,<1
    - pathlib2 >=2.2.1,<3
    - raven

test:
  imports:
    - floyd
    - floyd.cli
    - floyd.client
    - floyd.development
    - floyd.manager
    - floyd.model
  commands:
    - floyd --help
    - floyd-dev --help
    - floyd-local --help
  requires:
    - mock >=1.0.1
    - pytest

about:
  home: https://github.com/floydhub/floyd-cli
  license_family: AGPL
  license: Apache
  summary: Command line tool for Floyd
  doc_url: https://docs.floydhub.com
  description: README.md

extra:
  recipe-maintainers: 'support@floydhub.com'
